---
title: "MA 415 Assignment 1"
author: "Nicole Mis"
date: "January 22, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

#a 
1:20

#b
20:1

#c
c(1:20, 19:1)

#d
tmp <- c(4, 6, 3)

#e
e <- rep(tmp, times=10)

#f
f <- rep(tmp, length=31)

#g
y <- rep(tmp, times= c(10, 20, 30))

#2
x <- seq(3, 6, by=0.1)
y <- exp(x)*cos(x)

#3a
(0.1^seq(3,36, by=3))*(0.2^seq(1,34, by=3))

#3b
d <- c(1:25)
e <- 2^d/d

#4a
i <- c(10:100)
j <- sum(i^3 + 4*i^2)

#4b
i <- c(1:25)
j <- sum(2^i/i+3^i/i^2)

#5a
a <- paste("label", 1:30, sep=" ")

#5b
a <- paste("fn", 1:30, sep="")

#6
set.seed(50)
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)

#6a
yVec[-1]-xVec[-length(xVec)]
#or
yVec[2:length(yVec)]-xVec[1:length(xVec)-1]

#6b
newvec <- sin(yVec[-length(yVec)])/cos(xVec[-1])

#6c
lenvec <- length(xVec)
newvec <- xVec[-c(lenvec-1)] + 2*xVec[-c(1, lenvec)]-xVec[-c(1, 2)]
newvec <- xVec[-c(lenvec-1)] + 2*xVec[-c(1, lenvec)]-xVec[-c(1, 2)]
#6d
newvec <- sum(exp(-xVec[-1])/(xVec[-length(xVec)]+10))
              
#7a
yVec[yVec > 600]

#7b
which(yVec > 600)

#7c
xVec[yVec > 600]

#7d
sqrt(abs(xVec-mean(xVec)))

#7e
sum(yVec > (max(yVec)-200))

#7f
sum(xVec %% 2 == 0)

#7g
xVec[order(yVec)]

#7h
yVec[c(T, F, F)]

#or
yVec[(seq(1, length(yVec), 3))]

#8
1+sum(cumprod(seq(2,38,2)/seq(3,39,2)))



```
